CREATE DATABASE testDB;

DROP DATABASE testDB;

CREATE TABLE nationBack(
N_NATIONKEY INT NOT NULL,
N_NAME CHAR(25) NOT NULL,
N_REGIONKEY INT NOT NULL,
n_comment VARCHAR(152)
);

SHOW TABLES;

DROP TABLE nationBack;

DESC NATION;

INSERT INTO NATION VALUES (0,'America',0, 'nothing left');

INSERT INTO NATION VALUES ('id86','America',0, 'nothing left');

INSERT INTO ORDERS VALUES (127664,315000,'F',6.5,'2018/2/29',0,'Clerk101',1,'nice service');

DELETE FROM CUSTOMER WHERE C_CUSTKEY=5;

UPDATE PARTSUPP SET PS_AVAILQTY=8774 WHERE PS_PARTKEY=12;

SELECT * FROM CUSTOMER WHERE C_NATIONKEY<10;

SELECT O_ORDERDATE,O_TOTALPRICE FROM ORDERS WHERE O_ORDERDATE='1996-01-02';

SELECT CUSTOMER.C_PHONE, ORDERS.O_ORDERSTATUS FROM CUSTOMER,ORDERS where CUSTOMER.C_CUSTKEY=ORDERS.O_CUSTKEY, CUSTOMER.C_NAME='Customer#000000001';

UPDATE NATION SET N_REGIONKEY = 316001 WHERE N_NATIONKEY= 15;

ALTER TABLE NATION ADD column N_COMMENT_2 varchar(32);

ALTER TABLE NATION drop column N_COMMENT_2;

ALTER TABLE NATION RENAME TO PROVINCE;

ALTER TABLE NATION ADD PRIMARY KEY (N_NATIONKEY);

ALTER TABLE NATION ADD constraint NATION_FK1 FOREIGN KEY (N_REGIONKEY) references REGION(R_REGIONKEY);

ALTER TABLE NATION DROP FOREIGN KEY NATION_FK1;

ALTER TABLE CUSTOMER ADD INDEX Idx_residual(C_ACCTBAL);

ALTER TABLE CUSTOMER DROP INDEX Idx_residual;

SELECT MAX(P_SIZE) FROM PART;

SELECT AVG(P_SIZE) FROM PART;

SELECT MIN(P_SIZE) FROM PART;

SELECT SUM(P_SIZE) FROM PART;

SELECT O_TOTALPRICE FROM ORDERS WHERE O_CLERK like 'clerk%';

SELECT CUSTOMER.C_NAME, ORDERS.O_ORDERSTATUS, NATION.N_NATIONKEY FROM CUSTOMER, ORDERS, NATION WHERE CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY, CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY, NATION.N_NAME = 'CHINA';

SELECT CUSTOMER.C_NAME, ORDERS.O_ORDERSTATUS, NATION.N_NATIONKEY FROM CUSTOMER, ORDERS, NATION, REGION WHERE CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY, CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY, NATION.N_REGIONKEY = REGION.R_REGIONKEY, NATION.N_NAME='CHINA';

SELECT CUSTOMER.C_NAME, ORDERS.O_ORDERSTATUS, NATION.N_NATIONKEY FROM CUSTOMER, ORDERS, NATION, REGION, LINEITEM WHERE CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY, CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY, NATION.N_REGIONKEY = REGION.R_REGIONKEY, ORDERS.O_ORDERKEY = LINEITEM.L_ORDERKEY, NATION.N_NAME='CHINA';

SELECT MIN(O_TOTALPRICE), O_ORDERKEY FROM ORDERS GROUP BY O_ORDERKEY LIMIT 5;

SELECT * FROM CUSTOMER WHERE C_CUSTKEY IN (SELECT O_CUSTKEY FROM ORDERS WHERE O_TOTALPRICE > 10);

ALTER TABLE CUSTOMER ADD UNIQUE uidx_id(C_CUSTKEY);

ALTER TABLE NATION ADD CONSTRAINT fk_nation_region FOREIGN KEY(N_REGIONKEY) REFERENCES REGION(R_REGIONKEY) ON UPDATE CASCADE;

